# Generated by Django 5.2.14 on 2026-05-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('pattu', 'Pattu Sarees'), ('cotton', 'Cotton Sarees'), ('silk', 'Silk Sarees'), ('designer', 'Designer Sarees'), ('wedding', 'Wedding Sarees'), ('daily', 'Daily Wear Sarees')], max_length=30)),
                ('material', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('main_image', models.ImageField(upload_to='products/main/')),
                ('sub_image_1', models.ImageField(blank=True, null=True, upload_to='products/sub/')),
                ('sub_image_2', models.ImageField(blank=True, null=True, upload_to='products/sub/')),
                ('sub_image_3', models.ImageField(blank=True, null=True, upload_to='products/sub/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_available', '-created_at'], name='store_produ_categor_7d3baf_idx'), models.Index(fields=['is_new_arrival', 'is_available', '-created_at'], name='store_produ_is_new__f80b85_idx')],
            },
        ),
    ]
