# Generated by Django 5.2.14 on 2026-05-29 11:39

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to=store.models.product_main_image_upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.product_sub_image_upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.product_sub_image_upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.product_sub_image_upload_to),
        ),
    ]
