# Generated by Django 5.2.14 on 2026-05-30 11:28

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_color_code_product_color_name_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arrival_card_image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.product_arrival_card_image_upload_to),
        ),
    ]
