# Generated by Django 5.2.14 on 2026-05-30 12:04

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_arrival_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='arrival_card_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=store.models.product_arrival_card_image_upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(max_length=255, upload_to=store.models.product_main_image_upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_image_1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=store.models.product_sub_image_upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_image_2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=store.models.product_sub_image_upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_image_3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=store.models.product_sub_image_upload_to),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=store.models.product_variant_image_upload_to),
        ),
    ]
