# Generated by Django 5.2.14 on 2026-05-31 18:11

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_most_carted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_most_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_top_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='top_showcase_image',
            field=models.ImageField(blank=True, help_text='Optional image for homepage top carousel. If empty, main image can be used.', max_length=255, null=True, upload_to=store.models.product_top_showcase_image_upload_to),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_top_selling', 'is_available', '-created_at'], name='store_produ_is_top__6c42b5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_most_liked', 'is_available', '-created_at'], name='store_produ_is_most_dd8390_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_most_carted', 'is_available', '-created_at'], name='store_produ_is_most_c99fcc_idx'),
        ),
    ]
