# Generated by Django 5.2.14 on 2026-06-02 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_is_most_carted_product_is_most_liked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(blank=True, help_text='Example: Free Size, 38, M, 30, 4-5Y.', max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of pieces available.'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_size', 'is_available'], name='store_produ_product_06cdf3_idx'),
        ),
        migrations.AddField(
            model_name='producthighlight',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='store.product'),
        ),
        migrations.AddIndex(
            model_name='producthighlight',
            index=models.Index(fields=['product', 'sort_order'], name='store_produ_product_180afc_idx'),
        ),
    ]
