# Generated by Django 5.2.14 on 2026-06-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_producthighlight_product_product_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerHomePageRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Owner Home Page Row',
                'verbose_name_plural': 'Owner Home Page Rows',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
