# Generated by Django 5.2.14 on 2026-06-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_ownerhomepagerow'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='home_rows',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.ownerhomepagerow'),
        ),
    ]
