# Generated by Django 5.2.14 on 2026-06-19 16:59

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_ownerhomepagerow_display_after'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(help_text='Example: S, M, L, XL, 28, 32, Free Size.', max_length=40)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Number of pieces available in this size.')),
                ('measurement_unit', models.CharField(choices=[('in', 'Inches'), ('cm', 'Centimeters')], default='in', max_length=2)),
                ('chest', models.DecimalField(blank=True, decimal_places=2, help_text='Optional chest measurement for this size.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('waist', models.DecimalField(blank=True, decimal_places=2, help_text='Optional waist measurement for this size.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='Optional product length for this size.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_available', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSizeMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Example: Shoulder, Sleeve Length, Hip, Inseam.', max_length=60)),
                ('value', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(choices=[('in', 'Inches'), ('cm', 'Centimeters')], default='in', max_length=2)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_measurements', to='store.productsize')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='productsize',
            index=models.Index(fields=['product', 'is_available', 'sort_order'], name='store_produ_product_9e6820_idx'),
        ),
        migrations.AddIndex(
            model_name='productsize',
            index=models.Index(fields=['size_name'], name='store_produ_size_na_2aeea7_idx'),
        ),
        migrations.AddConstraint(
            model_name='productsize',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('size_name'), models.F('product'), name='unique_product_size_name_ci'),
        ),
        migrations.AddIndex(
            model_name='productsizemeasurement',
            index=models.Index(fields=['product_size', 'sort_order'], name='store_produ_product_395206_idx'),
        ),
        migrations.AddConstraint(
            model_name='productsizemeasurement',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('label'), models.F('product_size'), name='unique_product_size_measurement_label_ci'),
        ),
    ]
