# Generated by Django 5.2.14 on 2026-07-15 16:26

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_merchant_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_sub_image_1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=store.models.product_variant_image_upload_to),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_sub_image_2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=store.models.product_variant_image_upload_to),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_sub_image_3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=store.models.product_variant_image_upload_to),
        ),
    ]
